In [15]:
from pathlib import Path
import sys

project_root = Path.cwd().parent

sys.path.append(str(project_root))

from src.preprocessing import process_case

print("Pipeline imported successfully!")

Pipeline imported successfully!

In [16]:
df_case1 = process_case(1)

In [17]:
df_case1.head()

,minute,heart_rate,spo2,respiratory_rate,mean_arterial_pressure,spo2_valid_count,samples_in_minute,spo2_coverage,future_spo2_5min,spo2_lag_1,...,spo2_change_3min,spo2_rolling_mean_5,spo2_rolling_std_5,heart_rate_lag_1,heart_rate_rolling_mean_5,rr_lag_1,rr_rolling_mean_5,map_lag_1,map_rolling_mean_5,caseid
0,0,79.0,97.0,NaN,NaN,29,30,0.966667,100.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
1,1,85.0,97.0,NaN,NaN,30,30,1.000000,100.0,97.0,...,NaN,NaN,NaN,79.0,NaN,NaN,NaN,NaN,NaN,1
2,2,88.0,97.0,NaN,NaN,30,30,1.000000,100.0,97.0,...,NaN,97.00,0.00000,85.0,84.00,NaN,NaN,NaN,NaN,1
3,3,87.0,98.0,NaN,NaN,30,30,1.000000,100.0,97.0,...,1.0,97.25,0.50000,88.0,84.75,NaN,NaN,NaN,NaN,1
4,4,86.0,100.0,NaN,NaN,30,30,1.000000,100.0,98.0,...,3.0,97.80,1.30384,87.0,85.00,NaN,NaN,NaN,NaN,1

In [18]:
print("Shape:", df_case1.shape)

Shape: (193, 23)

In [19]:
df_case1[
    [
        "caseid",
        "minute",
        "spo2_lag_5",
        "spo2_lag_3",
        "spo2_lag_1",
        "spo2",
        "future_spo2_5min"
    ]
].head(15)

,caseid,minute,spo2_lag_5,spo2_lag_3,spo2_lag_1,spo2,future_spo2_5min
0,1,0,NaN,NaN,NaN,97.0,100.0
1,1,1,NaN,NaN,97.0,97.0,100.0
2,1,2,NaN,NaN,97.0,97.0,100.0
3,1,3,NaN,97.0,97.0,98.0,100.0
4,1,4,NaN,97.0,98.0,100.0,100.0
5,1,5,97.0,97.0,100.0,100.0,100.0
6,1,6,97.0,98.0,100.0,100.0,100.0
7,1,7,97.0,100.0,100.0,100.0,100.0
8,1,8,98.0,100.0,100.0,100.0,100.0
9,1,9,100.0,100.0,100.0,100.0,100.0
10,1,10,100.0,100.0,100.0,100.0,100.0
11,1,11,100.0,100.0,100.0,100.0,100.0
12,1,12,100.0,100.0,100.0,100.0,100.0
13,1,13,100.0,100.0,100.0,100.0,100.0
14,1,14,100.0,100.0,100.0,100.0,100.0

In [ ]:
df_case1 = process_case(1)

: